### ISSUE TITLE
Unresolved reference: stackTraceToString

### ISSUE THREAD

**Issue by oliverchu** [DRSchlaubi/contact_picker#23]
e: /Users/oliver/Work/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttercontactpicker-4.2.1/android/src/main/kotlin/me/schlaubi/fluttercontactpicker/ContactPicker.kt: (52, 280): Unresolved reference: stackTraceToString

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttercontactpicker:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

**Comment by britov** [comment]
I have the same problem

Until we are waiting accept of pull request (https://github.com/DRSchlaubi/contact_picker/pull/24)
We can use next
```
 fluttercontactpicker: # ^4.2.1
    git:
      url: https://github.com/britov/contact_picker.git
      ref: 0097f9f637272e9c9dcdea50d85833a44b02839e
      path: contact_picker
```
